# Numpy 연습문제

## 1. 길이가 10인 0-벡터를 만드세요.

In [8]:
import numpy as np
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

## 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [9]:
test_vector = np.zeros(shape=(10,), dtype=np.int8)
test_vector[4] = 1
test_vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

## 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [10]:
test_vector = np.arange(10,50)
test_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 4. 위(3번) 벡터의 순서를 바꾸세요.

In [11]:
np.flip(test_vector)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 5. 0부터 8까지의 값을 가지는 3X3 행렬을 만드세요.

In [12]:
test_arr = np.arange(0,9).reshape(3,3)
test_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6. 벡터 [1,2,0,0,4,0]에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [22]:
vector = np.array([1,2,0,0,4,0],int)
vector[vector!=0]

array([1, 2, 4])

## 7. 3X3 단위 행렬(identity matrix)을 만드세요

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8. 난수 원소를 가지는 3X3 행렬을 만드세요

In [55]:
np.random.seed(1000)
rand_arr = np.random.uniform(0,1,9).reshape(3,3)
rand_arr

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ]])

## 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요.

In [61]:
print('생성한 난수 행렬에서의 최대값 : ',np.max(rand_arr))
print('생성한 난수 행렬에서의 최소값 : ',np.min(rand_arr))

생성한 난수 행렬에서의 최대값 :  0.9502828643490245
생성한 난수 행렬에서의 최소값 :  0.040709624769089126


## 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [65]:
print('생성한 난수 행렬에서의 행 평균 : ',rand_arr.mean(axis=0))
print('생성한 난수 행렬에서의 열 평균 : ',rand_arr.mean(axis=1))

생성한 난수 행렬에서의 행 평균 :  [0.39216354 0.46155865 0.46524925]
생성한 난수 행렬에서의 열 평균 :  [0.5729598  0.52233287 0.22367876]
